function COM = COM_jumping_leg(in1,in2)
%COM_JUMPING_LEG
%    COM = COM_JUMPING_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    07-Nov-2021 00:16:33

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
dx = in1(9,:);
dy = in1(10,:);
l_AC = in2(20,:);
l_A_m3 = in2(15,:);
l_B_m2 = in2(14,:);
l_C_m4 = in2(16,:);
l_OA = in2(18,:);
l_OB = in2(19,:);
l_O_m1 = in2(13,:);
l_O_m5 = in2(17,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
m5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
x = in1(4,:);
y = in1(5,:);
t2 = cos(th1);
t3 = cos(th3);
t4 = sin(th1);
t5 = sin(th3);
t6 = th1+th2;
t15 = -y;
t19 = m1+m2+m3+m4+m5;
t7 = l_C_m4.*t2;
t8 = l_OA.*t2;
t9 = l_OB.*t2;
t10 = cos(t6);
t11 = l_C_m4.*t4;
t12 = l_OA.*t4;
t13 = l_OB.*t4;
t14 = sin(t6);
t23 = 1.0./t19;
t16 = l_AC.*t10;
t17 = l_A_m3.*t10;
t18 = l_B_m2.*t10;
t20 = l_AC.*t14;
t21 = l_A_m3.*t14;
t22 = l_B_m2.*t14;
COM = [t23.*(m3.*(t12+t21+x)+m2.*(t13+t22+x)+m1.*(x+l_O_m1.*t4)+m5.*(x+l_O_m5.*t5)+m4.*(t11+t12+t20+x));-t23.*(m3.*(t8+t15+t17)+m2.*(t9+t15+t18)-m1.*(y-l_O_m1.*t2)-m5.*(y-l_O_m5.*t3)+m4.*(t7+t8+t15+t16));dx+dth2.*t23.*(m2.*t18+m3.*t17+m4.*t16)+dth1.*t23.*(m3.*(t8+t17)+m2.*(t9+t18)+m4.*(t7+t8+t16)+l_O_m1.*m1.*t2)+dth3.*l_O_m5.*m5.*t3.*t23;dy+dth2.*t23.*(m2.*t22+m3.*t21+m4.*t20)+dth1.*t23.*(m3.*(t12+t21)+m2.*(t13+t22)+m4.*(t11+t12+t20)+l_O_m1.*m1.*t4)+dth3.*l_O_m5.*m5.*t5.*t23];
