function Corr_Joint_Sp = Corr_leg(in1,in2)
%CORR_LEG
%    CORR_JOINT_SP = CORR_LEG(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Nov-2021 14:56:39

dth1 = in1(6,:);
dth2 = in1(7,:);
dth3 = in1(8,:);
l_AC = in2(20,:);
l_A_m3 = in2(15,:);
l_B_m2 = in2(14,:);
l_C_m4 = in2(16,:);
l_OA = in2(18,:);
l_OB = in2(19,:);
l_O_m1 = in2(13,:);
l_O_m5 = in2(17,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
m5 = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
t2 = cos(th1);
t3 = sin(th1);
t4 = sin(th2);
t5 = th1+th2;
t6 = dth1.^2;
t7 = dth2.^2;
t8 = dth3.^2;
t9 = l_AC.*l_C_m4.*m4;
t10 = l_AC.*l_OA.*m4;
t11 = l_A_m3.*l_OA.*m3;
t12 = l_B_m2.*l_OB.*m2;
t13 = cos(t5);
t14 = sin(t5);
t15 = t9+t10+t11+t12;
Corr_Joint_Sp = [-dth2.*t4.*t15.*(dth1.*2.0+dth2);t4.*t6.*t15;0.0;-l_AC.*m4.*t6.*t14-l_AC.*m4.*t7.*t14-l_A_m3.*m3.*t6.*t14-l_A_m3.*m3.*t7.*t14-l_B_m2.*m2.*t6.*t14-l_B_m2.*m2.*t7.*t14-l_C_m4.*m4.*t3.*t6-l_OA.*m3.*t3.*t6-l_OB.*m2.*t3.*t6-l_OA.*m4.*t3.*t6-l_O_m1.*m1.*t3.*t6-l_O_m5.*m5.*t8.*sin(th3)-dth1.*dth2.*l_AC.*m4.*t14.*2.0-dth1.*dth2.*l_A_m3.*m3.*t14.*2.0-dth1.*dth2.*l_B_m2.*m2.*t14.*2.0;l_AC.*m4.*t6.*t13+l_AC.*m4.*t7.*t13+l_A_m3.*m3.*t6.*t13+l_A_m3.*m3.*t7.*t13+l_B_m2.*m2.*t6.*t13+l_B_m2.*m2.*t7.*t13+l_C_m4.*m4.*t2.*t6+l_OA.*m3.*t2.*t6+l_OB.*m2.*t2.*t6+l_OA.*m4.*t2.*t6+l_O_m1.*m1.*t2.*t6+l_O_m5.*m5.*t8.*cos(th3)+dth1.*dth2.*l_AC.*m4.*t13.*2.0+dth1.*dth2.*l_A_m3.*m3.*t13.*2.0+dth1.*dth2.*l_B_m2.*m2.*t13.*2.0];
