function rO = position_mount(in1,in2)
%POSITION_MOUNT
%    RO = POSITION_MOUNT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Nov-2021 21:14:02

x = in1(4,:);
y = in1(5,:);
rO = [x;y;0.0];
