function rB = position_hip(in1,in2)
%POSITION_HIP
%    RB = POSITION_HIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Nov-2021 21:14:02

l_OB = in2(19,:);
th1 = in1(1,:);
x = in1(4,:);
y = in1(5,:);
rB = [x+l_OB.*sin(th1);y-l_OB.*cos(th1);0.0];
