function rB = position_elbow(in1,in2)
%POSITION_ELBOW
%    RB = POSITION_ELBOW(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Nov-2021 13:51:41

l_OB = in2(19,:);
th1 = in1(1,:);
x = in1(4,:);
y = in1(5,:);
rB = [x+l_OB.*sin(th1);y-l_OB.*cos(th1);0.0];
