function r_m5 = position_swinging_foot(in1,in2)
%POSITION_SWINGING_FOOT
%    R_M5 = POSITION_SWINGING_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    04-Dec-2021 21:27:07

l_O_m5 = in2(17,:);
th3 = in1(3,:);
x = in1(4,:);
y = in1(5,:);
r_m5 = [x+l_O_m5.*sin(th3);y-l_O_m5.*cos(th3);0.0];
